In [1]:
import numpy as np

In [2]:
np_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [3]:
np_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Transpose np_array

In [4]:
np.transpose(np_array)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [5]:
np_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np_array.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## Reshape np_array

In [7]:
np.reshape(np_array, [9, 1])

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

## Split

Split np_array to have first two rows and last one row.

In [8]:
np_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.split(np_array, [2], 0)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9]])]

In [10]:
np.split(np_array, [1, 2], 0)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

Split np_array to have first two columns and last one column.

In [11]:
np.split(np_array, [2], 1)

[array([[1, 2],
        [4, 5],
        [7, 8]]),
 array([[3],
        [6],
        [9]])]

In [12]:
np.split(np_array, [1, 2], 1)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

## Concatenate

add the 4th row with 10, 11 and 12

In [13]:
np_array 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
row = np.array([[10, 11, 12]])

In [15]:
np.concatenate((np_array, row), 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

add the 4th column with 10, 11 and 12

In [16]:
col = np.array([[10], [11], [12]])

In [17]:
np.concatenate((np_array, col), 1)

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])