In [1]:
import numpy as np

In [2]:
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([-1, 5, 6])

In [3]:
np.cov(arr_1, arr_2)

array([[ 1.        ,  3.5       ],
       [ 3.5       , 14.33333333]])

In [4]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [5]:
np.histogram(arr, 3)

(array([3, 3, 4]), array([ 1.,  4.,  7., 10.]))

In [6]:
np.percentile(arr, [10, 90])

array([1.9, 9.1])

In [7]:
np.median(arr)

5.5

In [8]:
np.min(arr)

1

In [9]:
np.argmax(arr)

9