In [ ]:
import numpy as np

In [ ]:
array_1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_2 = np.array([[1, 2], [3, 4], [5, 6]])

## Linear Algebra
For array_1, 
- try matrix multiplication with array_2.
- calculate determinant, eigen value/vector, inverse matrix, and SVD

In [ ]:
np.dot(array_1, array_2)

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])

In [ ]:
np.linalg.det(array_1)

-9.51619735392994e-16

In [ ]:
np.linalg.eig(array_1)

(array([ 1.61168440e+01, -1.11684397e+00, -3.38433605e-16]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [ ]:
np.linalg.inv(array_1)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [ ]:
np.linalg.svd(array_1)

(array([[-0.21483724,  0.88723069,  0.40824829],
        [-0.52058739,  0.24964395, -0.81649658],
        [-0.82633754, -0.38794278,  0.40824829]]),
 array([1.68481034e+01, 1.06836951e+00, 3.33475287e-16]),
 array([[-0.47967118, -0.57236779, -0.66506441],
        [-0.77669099, -0.07568647,  0.62531805],
        [-0.40824829,  0.81649658, -0.40824829]]))