In [1]:
import numpy as np

In [15]:
for i in range(5):
    np.random.seed(1)
    print(np.random.randint(0, 100, 10))

[37 12 72  9 75  5 79 64 16  1]
[37 12 72  9 75  5 79 64 16  1]
[37 12 72  9 75  5 79 64 16  1]
[37 12 72  9 75  5 79 64 16  1]
[37 12 72  9 75  5 79 64 16  1]


In [19]:
for i in range(5):
    np.random.seed(1)
    print(np.random.normal(0, 1, 10))

[ 1.62434536 -0.61175641 -0.52817175 -1.07296862  0.86540763 -2.3015387
  1.74481176 -0.7612069   0.3190391  -0.24937038]
[ 1.62434536 -0.61175641 -0.52817175 -1.07296862  0.86540763 -2.3015387
  1.74481176 -0.7612069   0.3190391  -0.24937038]
[ 1.62434536 -0.61175641 -0.52817175 -1.07296862  0.86540763 -2.3015387
  1.74481176 -0.7612069   0.3190391  -0.24937038]
[ 1.62434536 -0.61175641 -0.52817175 -1.07296862  0.86540763 -2.3015387
  1.74481176 -0.7612069   0.3190391  -0.24937038]
[ 1.62434536 -0.61175641 -0.52817175 -1.07296862  0.86540763 -2.3015387
  1.74481176 -0.7612069   0.3190391  -0.24937038]


In [21]:
for i in range(5):
    np.random.seed(1)
    print(np.random.chisquare(1, 10))

[3.47814705e-01 2.61631977e-08 4.30745830e-02 6.93857327e-02
 3.14848857e-01 3.51448082e-01 8.36014448e-02 1.50016052e-03
 3.48286596e-01 3.94169851e-02]
[3.47814705e-01 2.61631977e-08 4.30745830e-02 6.93857327e-02
 3.14848857e-01 3.51448082e-01 8.36014448e-02 1.50016052e-03
 3.48286596e-01 3.94169851e-02]
[3.47814705e-01 2.61631977e-08 4.30745830e-02 6.93857327e-02
 3.14848857e-01 3.51448082e-01 8.36014448e-02 1.50016052e-03
 3.48286596e-01 3.94169851e-02]
[3.47814705e-01 2.61631977e-08 4.30745830e-02 6.93857327e-02
 3.14848857e-01 3.51448082e-01 8.36014448e-02 1.50016052e-03
 3.48286596e-01 3.94169851e-02]
[3.47814705e-01 2.61631977e-08 4.30745830e-02 6.93857327e-02
 3.14848857e-01 3.51448082e-01 8.36014448e-02 1.50016052e-03
 3.48286596e-01 3.94169851e-02]
